version: "3"

vars:
    PYTHON_VERSION: "3.12"

env:
    UV_PYTHON: "{{.PYTHON_VERSION}}"

tasks:
    default:
        desc: "Default task"
        cmds:
            - task --list

    install:
        desc: "Install dependencies"
        deps:
            - backend:install
            - frontend:install

    node:check:
        desc: "Ensure Node.js 24.x is installed"
        cmds:
            - |
              node -e "const major = process.versions.node.split('.')[0]; if (major !== '24') { console.error('Expected Node.js 24.x but found ' + process.versions.node); process.exit(1); }"

    python:check:
        desc: "Ensure Python 3.12.x is installed"
        silent: true
        cmds:
            - >
              uv run --python {{.PYTHON_VERSION}} python -c "import sys; major, minor = sys.version_info[:2];
              expected = (3, 12); actual = (major, minor);
              sys.stderr.write(f'Expected Python 3.12.x but found {sys.version.split()[0]}\n')
              if actual != expected else None; sys.exit(0 if actual == expected else 1)"

    test:
        desc: "Run tests"
        deps:
            - backend:test

    check:
        desc: "Run static analysis"
        deps:
            - backend:check
            - frontend:check

    backend:install:
        desc: "Install backend dependencies"
        dir: backend
        deps:
            - python:check
        cmds:
            - uv sync --frozen --python 3.12

    backend:test:
        desc: "Run backend tests"
        dir: backend
        deps:
            - python:check
        cmds:
            - uv run pytest

    backend:check:
        desc: "Run backend static analysis"
        deps:
            - python:check
            - backend:ruff
            - backend:ruff-format
            - backend:ty

    backend:ruff:
        desc: "Run backend ruff check"
        dir: backend
        deps:
            - python:check
        cmds:
            - uv run ruff check .

    backend:ruff-format:
        desc: "Run backend ruff format check"
        dir: backend
        deps:
            - python:check
        cmds:
            - uv run ruff format --check .

    backend:ty:
        desc: "Run backend ty check"
        dir: backend
        deps:
            - python:check
        cmds:
            - uv run ty check .

    backend:dev:
        desc: "Run backend dev server"
        dir: backend
        cmds:
            - uv run uvicorn app.main:app --reload

    backend:db-up:
        desc: "Start backend DB (docker compose)"
        dir: backend
        cmds:
            - docker compose up -d

    backend:db-down:
        desc: "Stop backend DB (docker compose)"
        dir: backend
        cmds:
            - docker compose down -v

    frontend:install:
        desc: "Install frontend dependencies"
        dir: frontend
        deps:
            - node:check
        cmds:
            - npm ci

    frontend:check:
        desc: "Run frontend lint"
        deps:
            - node:check
            - frontend:eslint

    frontend:eslint:
        desc: "Run frontend eslint"
        dir: frontend
        deps:
            - node:check
        cmds:
            - npm run lint

    frontend:dev:
        desc: "Run frontend dev server"
        dir: frontend
        deps:
            - node:check
        cmds:
            - npm run dev
