"""Initial migration

Revision ID: 7ae773981d43
Revises:
Create Date: 2025-12-21 13:56:45.431005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ae773981d43"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("role", sa.Enum("student", "teacher", name="userrole"), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "courses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_courses_teacher_id"), "courses", ["teacher_id"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("target_reviews_per_submission", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_assignments_course_id"), "assignments", ["course_id"], unique=False)
    op.create_table(
        "course_enrollments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "user_id", name="uq_course_enrollment"),
    )
    op.create_index(op.f("ix_course_enrollments_course_id"), "course_enrollments", ["course_id"], unique=False)
    op.create_index(op.f("ix_course_enrollments_user_id"), "course_enrollments", ["user_id"], unique=False)
    op.create_table(
        "rubric_criteria",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("max_score", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rubric_criteria_assignment_id"), "rubric_criteria", ["assignment_id"], unique=False)
    op.create_table(
        "submissions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("file_type", sa.Enum("pdf", "markdown", name="submissionfiletype"), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_path", sa.String(length=500), nullable=False),
        sa.Column("markdown_text", sa.Text(), nullable=True),
        sa.Column("submission_text", sa.Text(), nullable=True),
        sa.Column("teacher_total_score", sa.Integer(), nullable=True),
        sa.Column("teacher_feedback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_submissions_assignment_id"), "submissions", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_submissions_author_id"), "submissions", ["author_id"], unique=False)
    op.create_table(
        "review_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("assigned", "submitted", name="reviewassignmentstatus"), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["reviewer_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "reviewer_id", name="uq_submission_reviewer"),
    )
    op.create_index(op.f("ix_review_assignments_assignment_id"), "review_assignments", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_review_assignments_reviewer_id"), "review_assignments", ["reviewer_id"], unique=False)
    op.create_index(op.f("ix_review_assignments_submission_id"), "review_assignments", ["submission_id"], unique=False)
    op.create_table(
        "submission_rubric_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["criterion_id"], ["rubric_criteria.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_submission_rubric_scores_criterion_id"),
        "submission_rubric_scores",
        ["criterion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_submission_rubric_scores_submission_id"),
        "submission_rubric_scores",
        ["submission_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_assignment_id", sa.Uuid(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ai_quality_score", sa.Integer(), nullable=True),
        sa.Column("ai_quality_reason", sa.Text(), nullable=True),
        sa.Column("ai_toxic", sa.Boolean(), nullable=True),
        sa.Column("ai_toxic_reason", sa.Text(), nullable=True),
        sa.Column("ai_logic", sa.Integer(), nullable=True),
        sa.Column("ai_specificity", sa.Integer(), nullable=True),
        sa.Column("ai_empathy", sa.Integer(), nullable=True),
        sa.Column("ai_insight", sa.Integer(), nullable=True),
        sa.Column("ai_comment_alignment_score", sa.Integer(), nullable=True),
        sa.Column("ai_comment_alignment_reason", sa.Text(), nullable=True),
        sa.Column("normalized_comment_hash", sa.String(length=64), nullable=True),
        sa.Column("duplicate_of_review_id", sa.Uuid(), nullable=True),
        sa.Column("duplicate_warning", sa.Text(), nullable=True),
        sa.Column("duplicate_penalty_rate", sa.Float(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.Column("similar_review_id", sa.Uuid(), nullable=True),
        sa.Column("similarity_warning", sa.Text(), nullable=True),
        sa.Column("similarity_penalty_rate", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["duplicate_of_review_id"], ["reviews.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["review_assignment_id"], ["review_assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["similar_review_id"], ["reviews.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_duplicate_of_review_id"), "reviews", ["duplicate_of_review_id"], unique=False)
    op.create_index(op.f("ix_reviews_normalized_comment_hash"), "reviews", ["normalized_comment_hash"], unique=False)
    op.create_index(op.f("ix_reviews_review_assignment_id"), "reviews", ["review_assignment_id"], unique=True)
    op.create_index(op.f("ix_reviews_similar_review_id"), "reviews", ["similar_review_id"], unique=False)
    op.create_table(
        "ta_review_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=False),
        sa.Column("submission_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("ta_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.Enum("offered", "accepted", "declined", name="tareviewrequeststatus"), nullable=False),
        sa.Column("review_assignment_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["assignment_id"], ["assignments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_assignment_id"], ["review_assignments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ta_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "ta_id", name="uq_submission_ta"),
    )
    op.create_index(op.f("ix_ta_review_requests_assignment_id"), "ta_review_requests", ["assignment_id"], unique=False)
    op.create_index(
        op.f("ix_ta_review_requests_review_assignment_id"),
        "ta_review_requests",
        ["review_assignment_id"],
        unique=False,
    )
    op.create_index(op.f("ix_ta_review_requests_submission_id"), "ta_review_requests", ["submission_id"], unique=False)
    op.create_index(op.f("ix_ta_review_requests_ta_id"), "ta_review_requests", ["ta_id"], unique=False)
    op.create_index(op.f("ix_ta_review_requests_teacher_id"), "ta_review_requests", ["teacher_id"], unique=False)
    op.create_table(
        "meta_reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("rater_id", sa.Uuid(), nullable=False),
        sa.Column("helpfulness", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["rater_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", name="uq_meta_review_review"),
    )
    op.create_index(op.f("ix_meta_reviews_rater_id"), "meta_reviews", ["rater_id"], unique=False)
    op.create_index(op.f("ix_meta_reviews_review_id"), "meta_reviews", ["review_id"], unique=False)
    op.create_table(
        "review_rubric_scores",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("review_id", sa.Uuid(), nullable=False),
        sa.Column("criterion_id", sa.Uuid(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["criterion_id"], ["rubric_criteria.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("review_id", "criterion_id", name="uq_review_criterion"),
    )
    op.create_index(
        op.f("ix_review_rubric_scores_criterion_id"),
        "review_rubric_scores",
        ["criterion_id"],
        unique=False,
    )
    op.create_index(op.f("ix_review_rubric_scores_review_id"), "review_rubric_scores", ["review_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_rubric_scores_review_id"), table_name="review_rubric_scores")
    op.drop_index(op.f("ix_review_rubric_scores_criterion_id"), table_name="review_rubric_scores")
    op.drop_table("review_rubric_scores")
    op.drop_index(op.f("ix_meta_reviews_review_id"), table_name="meta_reviews")
    op.drop_index(op.f("ix_meta_reviews_rater_id"), table_name="meta_reviews")
    op.drop_table("meta_reviews")
    op.drop_index(op.f("ix_ta_review_requests_teacher_id"), table_name="ta_review_requests")
    op.drop_index(op.f("ix_ta_review_requests_ta_id"), table_name="ta_review_requests")
    op.drop_index(op.f("ix_ta_review_requests_submission_id"), table_name="ta_review_requests")
    op.drop_index(op.f("ix_ta_review_requests_review_assignment_id"), table_name="ta_review_requests")
    op.drop_index(op.f("ix_ta_review_requests_assignment_id"), table_name="ta_review_requests")
    op.drop_table("ta_review_requests")
    op.drop_index(op.f("ix_reviews_similar_review_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_review_assignment_id"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_normalized_comment_hash"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_duplicate_of_review_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(op.f("ix_submission_rubric_scores_submission_id"), table_name="submission_rubric_scores")
    op.drop_index(op.f("ix_submission_rubric_scores_criterion_id"), table_name="submission_rubric_scores")
    op.drop_table("submission_rubric_scores")
    op.drop_index(op.f("ix_review_assignments_submission_id"), table_name="review_assignments")
    op.drop_index(op.f("ix_review_assignments_reviewer_id"), table_name="review_assignments")
    op.drop_index(op.f("ix_review_assignments_assignment_id"), table_name="review_assignments")
    op.drop_table("review_assignments")
    op.drop_index(op.f("ix_submissions_author_id"), table_name="submissions")
    op.drop_index(op.f("ix_submissions_assignment_id"), table_name="submissions")
    op.drop_table("submissions")
    op.drop_index(op.f("ix_rubric_criteria_assignment_id"), table_name="rubric_criteria")
    op.drop_table("rubric_criteria")
    op.drop_index(op.f("ix_course_enrollments_user_id"), table_name="course_enrollments")
    op.drop_index(op.f("ix_course_enrollments_course_id"), table_name="course_enrollments")
    op.drop_table("course_enrollments")
    op.drop_index(op.f("ix_assignments_course_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_courses_teacher_id"), table_name="courses")
    op.drop_table("courses")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
